### ISSUE TITLE
`get` matcher doesn't avoid `default`

### ISSUE THREAD

**Issue by matiasgarciaisaia** [soveran/toro#10]
I'm trying `toro` at version `d4409e03101aa981cfd063b0a6607da163e411b6` using Crystal 0.18.7 (2016-08-05) on OSX.

I've just read the `README.md`, and trimmed it like this:

```crystal
require "toro"

class App < Toro::Router
  def routes
    get do
      text "Hello world"
    end

    on "test" do
      text "This is a test"
    end

    default do
      text "This could be a 404 page"
    end
  end
end

App.run
```

The `/test` and `/non-existent` routes work OK, but I don't think `/` does what it should:

```
$ curl localhost:8080/test
This is a test
$ curl localhost:8080/non-existant
This could be a 404 page
$ curl localhost:8080
Hello world
This could be a 404 page
```

From the README.md example, I was hoping `/` would match the `get` expression - so `default` wouldn't happen.

I'm not sure if this is a bug in toro, if I misunderstood the docs, or if the docs are misleading.

Any help on this?

Thanks :)

**Comment by ray-delossantos** [comment]
Hi:

You can do this for returning when a http get request for "/".

``` crystal
require "toro"

class App < Toro::Router
  def routes
    get do
      text "Hello world"
      return
    end

    on "test" do
      text "This is a test"
    end

    default do
      text "This could be a 404 page"
    end
  end
end

App.run

```

**Comment by soveran** [comment]
Hey @matiasgarciaisaia, it is indeed unintended behavior. What you expected is what I expected too, so I'll try to find a way to make it work as you described. In the meantime, what @raydf suggests is a good workaround. Thanks a lot for reporting this and thanks @raydf for the continued help!

**Comment by soveran** [comment]
I just pushed a new version that defines all the verb matchers as macros. That fixes the behavior described in this issue. I tried to define the macros inside the same loop that defined the previous methods, but it didn't work. I will try to find out more about that approach later, but for now it works fine and I'm happy with the result.

@matiasgarciaisaia, @raydf: if you think this change fixes the issue, let me know and I will create a new release.

**Comment by matiasgarciaisaia** [comment]
@soveran the new version indeed fixes the issue.

Thanks for the quick response! 🎉

**Comment by ray-delossantos** [comment]
@soveran, as enhancement i believe there's a way to create a macro from a macro, maybe this way the code could be similar to the original version with the methods loop, anyways, as @matiasgarciaisaia says it works this way 👍.

**Comment by soveran** [comment]
Excellent, I just pushed version 0.3.3. I'll check later if we can create a macro in the loop. Thanks a lot!
