### ISSUE TITLE
Using middlewares

### ISSUE THREAD

**Issue by rogeriozambon** [soveran/toro#11]
Hey @soveran, great work with Toro!

I'm using this library for build an application but I need to use some middlewares. In `self.run` method is defined a splat parameter:

```ruby
def self.run(*args, &block)
  server = HTTP::Server.new(*args) do |context|
    call(context)
  end

  ...
end
```

But when I tried to specify the server parameters, this error was thrown:

```bash
Error in src/app.cr:51: wrong number of arguments for 'App::Service::Router.run' (given 3, expected 0..1)
Overloads are:
 - Toro::Router.run(port = 8080)
```

And the code that I'm running is:

```ruby
App::Service::Router.run("0.0.0.0", 2300, [App::Service::Middleware.new])
```

Is there an alternative to use middlewares with Toro?

**Comment by soveran** [comment]
I just tried the following example and it worked:

```crystal
App.run("0.0.0.0", 8080, [HTTP::LogHandler.new])
```

Which version of Toro are you using?

**Comment by rogeriozambon** [comment]
@soveran, that's the point 😞

I was using **0.3.3** version. Thanks!

**Comment by soveran** [comment]
@rogeriozambon No problem!
