### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [soveran/toro#13]
crystal run app.cr                                                                                    1 :( 10/30/19 -  8:26 
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'mount'

Code in app.cr:66:7

 66 | mount Guests
      ^
Called macro defined in lib/toro/src/toro.cr:141:5

 141 | macro mount(app)

Which expanded to:

 > 1 | Guests.call(context, path)
       ^-----
Error: undefined constant Guests

Crystal 0.31.1
Linux Manjaro

**Comment by soveran** [comment]
For some (silly) reason, I never expected that code to be copied, pasted and ran. It showcases different features but now I realize you are rightly surprised that it doesn't work out of the box.

There are two things to change for it to work:
1. The sub-application `Guests` must be defined; and
2. A template called `"views/users/show.ecr"` should exist.

Do you think adding those definitions would be enough? Or maybe it would be better to have a "hello world" application that can be copied and pasted, without the need of creating the `"views/users/show.ecr"` template?

Let me know what you think, and thanks a lot for reporting this issue.

**Comment by LeandroRezendeCoutinho** [comment]
Hello @soveran . Thanks for the answer. I really think you should put an application that can be copied. For first time use, is very convenient to have this. I make a test in other moment and i can't make it work. So i gave up. Because gives the impression of not working. But i know your other project Cuba. It is awesome, very simple and fast. So I decided to give it another try. I imagine if it runs on crystal it was going to be phenomenal.

**Comment by soveran** [comment]
I just updated the README. I added a short `hello world` example and fixed the other one so that you can copy and paste the content and it will work. Let me know what you think about it.

**Comment by LeandroRezendeCoutinho** [comment]
Thanks! Both works great. Now any one can just try and get succes without get in docs.
Some results:

ab -n 10000 -c 1000 http://localhost:8080/users/about

Concurrency Level:      1000
Time taken for tests:   0.666 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      820000 bytes
HTML transferred:       170000 bytes
**Requests per second:    15007.11 [#/sec] (mean)**
Time per request:       66.635 [ms] (mean)
Time per request:       0.067 [ms] (mean, across all concurrent requests)
Transfer rate:          1201.74 [Kbytes/sec] received

**Comment by soveran** [comment]
Excellent, thank you for bringing up this issue!
